### PR TITLE
Dotas 67

### PR DESCRIPTION
**Pull request by kssonu4u**

### CODE REVIEW

**Comment by southernsun** [comment]
in dw_stage.sh, i would rather see date formatting, such as:

export DATE=$(date -d '-3 day' +%Y/%m/%d)
or
export DATE_STR=$(date -d ${DATE} +%Y%m%d)

then this
export DATE_IN_S3_FORMAT=$(echo ${d:0:4}/${d:4:2}/${d:6:2})

can't you already use $DATE ?

**Comment by kssonu4u** [comment]
reason I use export DATE_IN_S3_FORMAT=$(echo ${d:0:4}/${d:4:2}/${d:6:2}) is because there is for loop (see below) and all the copying business logic is inside that,I was not sure if the DATE at top and d will be same always.And then what is the use of for loop then?
for d in ${DATE_TOKS}
do
    export DATE_IN_S3_FORMAT=$(echo ${d:0:4}/${d:4:2}/${d:6:2})

**Comment by southernsun** [comment]
that is true, but i would prefer if use the similar technique instead of echo with string fragmentation, so use something like "export DATE_IN_S3_FORMAT=$(date -d ${d} +%Y/%m/%d)"

**Comment by kssonu4u** [comment]
Done the required changes and tested it,it is working fine

**Pull request merged**
